#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history # share command history data

export EDITOR=vim
export PIPENV_COLORBLIND=1

alias genpass="cat /dev/urandom | LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1"

# Docker aliases
alias drmi='docker rmi $(docker images --filter dangling=true --quiet)'
alias drmc='docker rm $(docker ps -aq --filter status=exited)'

# Git aliases
alias gitl='git log --oneline --graph --decorate --all'
alias gitclean='git branch --merged master|grep -v "^[ *]*master$"|xargs git branch -d'
function gitlo() {
  git log --graph --pretty=format:'%Cred%h%Creset %C(bold blue)<%an>%Creset %Cred%x09%ai%Creset %C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative
}

# Python aliases
alias watchtest='. bin/activate && git ls-files|entr nosetests --ignore-files=flycheck* tests'

# Golang
export GOROOT="$(brew --prefix golang)/libexec"
export GOPATH="${HOME}/.go"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

# google cloud
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

alias filetree="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'"
alias history='fc -il 1'
alias make-folder-image='ffmpeg -i "`ls -1|head -1`" -an -vcodec copy Folder.jpg'

# python
export PATH="~/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

alias k='kubectl -n $NAMESPACE'

eval "$(direnv hook zsh)"
